// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlfctacdvpssgqinxjmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZmN0YWNkdnBzc2dxaW54am1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTA1MzUsImV4cCI6MjA2MTM4NjUzNX0.FsnfVcEWTWjFUmjBthOYyuqL05xBfsbA1GjJGhvQsA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);